repos:
  - repo: https://github.com/omnicate/pre-commit-dep-downloader
    rev: db52d5a7bbab2f1acae0d12c2e84c1db783d8060
    hooks:
      - id: dep-downloader
        name: "Download dependencies (brew, go)"
        args: ["--brew-packages=shellcheck"]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck
